- include/solvers/mpm_semi_implicit_twophase.tcc
This PR fixes the doubling of the force vector component when MPI is used. The error is there, but it won't bother the computation as of now due to the predictor-corrector scheme.
Occur more obviously in the implicit solver (PR https://github.com/geomechanics/mpm/pull/4).
> Fix force doubling in 2Phase when MPI is used

- include/linear_solvers/assemblers/assembler_eigen_implicit_linear.tcc
- include/solvers/mpm_implicit_linear.tcc
This PR modifies the assembly procedure of sparse matrices from direct memory access to tripletList. TripletList is conceptually a vector of `Eigen::Triplet<double>` which contains 2 indices and a double. 
https://github.com/geomechanics/mpm/pull/4, https://github.com/geomechanics/mpm/pull/5
This construction can improve the simulation time 1.5 times faster in `ImplicitLinear` solver. Though I need to run some benchmarks for other multi-phase solvers.
> [Feature] Fast matrix assembly

- include/particles/particle_implicit.tcc
This PR fixes a bug of the function "reduce_dmatrix" for the implicit 2D analysis.
The dmatrix for 2D should include the 4th row and 4th column of the original dmatrix,
but the previous code uses the 5th row and 5th column.
Nothing.
Nothing.
> [Bugfix] Reduction of dmatrix for 2D

- .circleci/config.yml
- include/cells/cell.tcc
- include/cells/cell_implicit.tcc
- include/cells/cell_multiphase.tcc
- include/elements/2d/quadrilateral_bspline_element.tcc
- include/elements/2d/quadrilateral_element.tcc
- include/elements/2d/triangle_element.tcc
- include/elements/3d/hexahedron_bspline_element.tcc
- include/elements/3d/hexahedron_element.tcc
- include/linear_solvers/assemblers/assembler_eigen_implicit.tcc
- include/linear_solvers/assemblers/assembler_eigen_semi_implicit_navierstokes.tcc
- include/linear_solvers/assemblers/assembler_eigen_semi_implicit_twophase.tcc
- include/linear_solvers/linear_solvers/krylov_petsc.h
- include/materials/mohr_coulomb.tcc
- include/mesh/mesh_multiphase.tcc
- include/nodes/node.tcc
- include/nodes/node_multiphase.tcc
- include/particles/particle.tcc
- include/particles/particle_fluid.tcc
- include/particles/particle_implicit.tcc
- include/particles/particle_twophase.tcc
- tests/particles/particle_test.cc
- tests/particles/particle_twophase_test.cc
While checking the performance for PR #27, I came to know that the matrix-matrix multiplication of `BDB^T` in computing stiffness matrix is quite a bottleneck of our implicit formulation. One suggestion is to do matrix no aliasing, which basically improves the memory allocation. This improves only a bit in parallel, but it seems it can help to fasten the code in a single thread.
In my 2D beam test with LME, before it takes 82s to run, and after this modification, it goes down to 55s. It's quite significant, but maybe that's just because the LME itself is not optimized yet.
I decided to do a global modification of the code. Could you please help me to check this PR for implicit and explicit solvers compared to master? @RyotaHashimoto @jgiven100. I will check the …
> [Feature] Matrix noaliasing

- include/materials/modified_cam_clay.tcc
- include/materials/norsand.tcc
- include/solvers/mpm_base.tcc
Remove unecessary zeros from `compute_elastic_tensor(...)` in NorSand and Modified Cam Clay models. 
Quick calculations show that current implementation is about `1.5x` times slower than the proposed improvements. 
>This is approximated by tracking time to complete 1,000,000 function calls with and without the extra zero assignment. The 1,000,000 function calls was completed for 10 sets and averaged.
>```
>1000000 function calls per set
>10 sets
>
>average run time                  : 2174.55 [ms]
>average run time (explicit zeros) : 3433.09 [ms]
>```
None
None
> [Fix] Remove unnecessary zeros

- include/particles/particle_finite_strain.h
- include/particles/particle_finite_strain.tcc
This PR adds (rather minor) enhancements to the finite-strain analysis as follow:
1. Correction in dn_dx in large deformation. As suggested by @migmolper, I am adding a recomputation process of `dn_dx_` at each iteration, by multiplying the `reference_dn_dx_` with the computed `deformation_gradient_increment_`. For a very large time step (dt=0.1s), it is shown to slightly improve the convergence rate in a 3D beam problem.
- Current code: 10 iterations/step (threshold)
- Proposed code: 7/8 iterations/step
The obtained results also slightly conserve the energy better (comparison is coming).
PR https://github.com/geomechanics/mpm/pull/45.
I am opening this PR for further discussions.
> [Particle] Several enhancement of particle finite strains

- include/particles/particle_base.h
- include/solvers/mpm_base.tcc
- tests/io/write_mesh_particles.cc
There is a bug to initialise pore pressure with the water table. The previous code passed `gravity_` which was not yet initialized by the `initialise_loads()` function. The proposed code reads gravity from the exact location as the load if desired by the initializer.
N/A
I added an extra test to check the initialization.
> [Bug] Water table initialization

- external/catch.hpp
This PR adds the following modification to `catch.hpp`:
1. Fix https://github.com/geomechanics/mpm/issues/61 since `SIGSTKSZ` is not a constant anymore in libc6 2.34.
2. Add arm64 support to `catch.hpp`.
Issue https://github.com/geomechanics/mpm/issues/61
This PR enhances the possibility to compile in Linux Ubuntu 22.04 and MacBook M1 arm64 chips.
> [Compile] SIGSTKSZ fix and add arm64 support

- include/cells/cell.h
- include/cells/cell.tcc
- include/elements/2d/quadrilateral_bspline_element.h
- include/elements/2d/quadrilateral_element.h
- include/elements/2d/quadrilateral_gimp_element.h
- include/elements/2d/quadrilateral_lme_element.h
- include/elements/2d/triangle_element.h
- include/elements/2d/triangle_lme_element.h
- include/elements/3d/hexahedron_bspline_element.h
- include/elements/3d/hexahedron_element.h
- include/elements/3d/hexahedron_gimp_element.h
- include/elements/3d/hexahedron_lme_element.h
- include/elements/3d/tetrahedron_element.h
- include/elements/element.h
- include/mesh/mesh_multiphase.tcc
- tests/cells/cell_test.cc
- tests/elements/hexahedron_bspline_element_test.cc
- tests/elements/hexahedron_element_test.cc
- tests/elements/hexahedron_gimp_element_test.cc
- tests/elements/hexahedron_lme_element_test.cc
- tests/elements/quadrilateral_bspline_element_test.cc
- tests/elements/quadrilateral_element_test.cc
- tests/elements/quadrilateral_gimp_element_test.cc
- tests/elements/quadrilateral_lme_element_test.cc
- tests/elements/tetrahedron_element_test.cc
- tests/elements/triangle_element_test.cc
- tests/elements/triangle_lme_element_test.cc
This PR introduces a fix to the free surface detection routine for nonlocal elements. Instead of using the regular `node_id`, which includes non-local nodes from adjacent cells, we should use `local_nodes_id`, which only contains the id of nodes located in the current cell of interest.
N/A
No change in the performance for local shape function. Also, tests are added to maintain code coverage.
> [Bugfix] Free surface detection for nonlocal elements

- CMakeLists.txt
- include/particles/particle_base.h
- include/particles/particle_fluid.h
- include/particles/particle_fluid.tcc
- include/particles/particle_twophase.h
- include/particles/particle_twophase.tcc
- include/solvers/mpm_semi_implicit_twophase.tcc
- tests/particles/particle_serialize_deserialize_fluid_test.cc
- tests/particles/particle_serialize_deserialize_twophase_test.cc
- tests/particles/particle_test.cc
This PR provides a remedy to fix problems observed in #68. 
1. This PR reverts back PR #6 which introduces kinematic field errors.
2. This PR also introduces serializing and deserializing of projection parameter which was not transferred before. Similar mitigation has been added to fluid particles as it will cause future issues if it is not treated as well.
Issues #68
1. Related issues should occur as well in the fluid-particle run by the Navier-stokes solver. Thus, additional actions are made to provide future problems.
2. Some tests have been added to further improve coverages.
> [MPI] Two-phase semi-implicit Issues

- include/particles/pod_particles/pod_particle.h
`PODParticle` struct needs to have the same order as data in `pod_particle.cc`.
I tested this by looking at a simple column at `step=0`. Its clear the particles should be in cells 0 thru 9.
```
df = pd.read_hdf(input_filename)
Id = np.array(df['id'])
Cell = np.array(df['cell_id'])
cells = np.array([Id[:], Cell[:]])
print(cells.transpose())
[[  0   1]
[  1   1]
[  2   1]
...
[637   1]
[638   1]
[639   1]]
```
These are obviously wrong values for the `"cell_id"`. Also, the 2nd column will contain random garbage values at intermediate rows. 
```
df = pd.read_hdf(input_filename)
Id = np.array(df['id'])
Status = np.array(df['status'])
cells = np.array([Id[:], Status[:]])
print(cells.transpose())
[[  0   0]
[  1   0]
[  2   0]
...
[637   9]
[638   9]
[639   9]]
```
The …
> [Bugfix] Swap status and cell_id for better HDF5 experience

- include/linear_solvers/linear_solvers/krylov_petsc.tcc
- include/mesh/mesh.h
- include/mesh/mesh_multiphase.tcc
- include/solvers/mpm_explicit_twophase.h
- include/solvers/mpm_explicit_twophase.tcc
- include/solvers/mpm_implicit.h
- include/solvers/mpm_semi_implicit_navierstokes.h
- include/solvers/mpm_semi_implicit_navierstokes.tcc
- include/solvers/mpm_semi_implicit_twophase.h
- include/solvers/mpm_semi_implicit_twophase.tcc
PR #71 previously added the capabilities to detect local elements in the vicinity of free surfaces, which reduce the "over" imposition region if the nonlocal elements are used. However, there is still some limitation to handle splashes and fragmentation of liquid particles in nonlocal elements. The splashes cause the coefficient matrix in the Poisson solver to be ill-conditioned and introduce spurious pressure value.
This PR fixes that issues and make the free-surface detection works better to handle splashes.
#71 
1. I also refactored the free-surface detection default parameters in the semi-implicit solvers, i.e. Navier-Stokes and two-phase.
2. Some snapshots of a water drop in the old code show the ill-condition …
> [Fluid] Add a fix in nonlocal free-surface detection algorithm

- include/elements/2d/quadrilateral_bspline_element.tcc
- include/elements/2d/quadrilateral_lme_element.tcc
- include/elements/2d/triangle_lme_element.tcc
- include/elements/3d/hexahedron_bspline_element.tcc
- include/elements/3d/hexahedron_element.tcc
- include/elements/3d/hexahedron_lme_element.tcc
- tests/elements/hexahedron_lme_element_test.cc
This PR fixes a bug in two functions: `jacobian` and `bmatrix` in high-order elements other than the GIMP. The former way is incorrect since the bspline and lme shape functions directly compute `dN/dx` not `dN/dxi` like the local shape function or GIMP. The proposed fix is to call the basis element functions.
N/A
Some minor fix in tests has been also done.
> [Element] High-order elements jacobian and bmatrix computation

- include/elements/2d/quadrilateral_lme_element.h
- include/elements/2d/quadrilateral_lme_element.tcc
- include/elements/2d/triangle_lme_element.h
- include/elements/2d/triangle_lme_element.tcc
- include/elements/3d/hexahedron_lme_element.h
- include/elements/3d/hexahedron_lme_element.tcc
This PR fixes an issue with LME convergence at a lower gamma value. The preconditioner added following Mathieu Foca causes the Newton-Raphson loop in LME elements to converge slower than expected, especially for gamma less than 6.0. For gamma larger than 6.0, the preconditioner is proven to be helpful to guarantee convergence, even with a slower rate. In order to accommodate the above, I propose adding an additional boolean that is going to tell whether a preconditioner should be applied or not.
N/A
N/A
> [Bugfix] LME convergence

- CMakeLists.txt
- include/io/io_mesh.h
- include/io/io_mesh_ascii.h
- include/io/io_mesh_ascii.tcc
- include/loads_bcs/adhesion_constraint.h
- include/loads_bcs/constraints.h
- include/loads_bcs/constraints.tcc
- include/nodes/node.h
- include/nodes/node.tcc
- include/nodes/node_base.h
- include/solvers/mpm_base.h
- include/solvers/mpm_base.tcc
- tests/include/write_mesh_particles.h
- tests/io/io_mesh_ascii_test.cc
- tests/io/write_mesh_particles.cc
- tests/mesh/mesh_test_2d.cc
- tests/mesh/mesh_test_3d.cc
- tests/nodes/node_test.cc
- tests/nodes/node_twophase_test.cc
- tests/solvers/mpm_explicit_constraint_adhesion_test.cc
**Description**
Small nomenclature change for boundary conditions: updated term cohesion to adhesion, as well as any related nomenclature.
**Reason**
- Terminology correction
- Make things easier to distinguish between constitutive property cohesion and boundary condition property adhesion
- Will make things consistent with levelset PR
> BC nomenclature cohesion to adhesion :truck:

- include/solvers/mpm_base.tcc
Added option to input "none"  for Cauchy stress rate without throwing a warning. Wiki also updated.
> optional input for cauchy stress rate :adhesive_bandage: :goal_net:

- include/materials/infinitesimal_strain/linear_elastic.tcc
Upon merging PR https://github.com/geomechanics/mpm/pull/93, I realized that if any of the derived elasto-plastic materials do not have the variables needed for the linear elastic model, the information of `stress_rate` will not be read and, hence, set as `mpm::StressRate::None`. This PR fixes the reading order so that the bug can be fixed.
PR https://github.com/geomechanics/mpm/pull/93
N/A
> [Bugfix] Change order of assigning stress_rate in linear elastic model

- include/particles/particle.tcc
- include/solvers/mpm_base.h
- include/solvers/mpm_base.tcc
- tests/io/write_mesh_particles.cc
- tests/particles/particle_test.cc
**Description**
VTK (.vtp) output options edited:
- "id" option for particle ID.
- "material" option for material ID (solid phase only).
- "geometry" option is now available, otherwise geometry no longer outputs (previously was output by default).
**TODO**
> [IO] VTK Outputs - id, materials, geometry (optional)

- include/solvers/mpm_base.h
- include/solvers/mpm_explicit_twophase.tcc
- include/solvers/mpm_scheme/mpm_scheme.h
- include/solvers/mpm_scheme/mpm_scheme.tcc
- include/solvers/mpm_semi_implicit_navierstokes.tcc
- include/solvers/mpm_semi_implicit_twophase.tcc
**Description**
Error changes for particles outside mesh domain:
- Particles leaving mesh domain will now have their IDs listed (' ' delimiter) in the error message.
- Extra string stream only created when `"locate_particles": true` in mpm.json input file.
- Requires `#include <sstream>` in `mpm_scheme.h` and `mpm_base.h`.
- This does NOT apply to errors called upon initialization (i.e., due to pre-processing) or resume. This is left without IDs listed because incorrect pre-processing could result in a list of millions of particle IDs.
Example of new console output:
> [Clean-up] MP IDs outside mesh domain listed with error

- include/materials/infinitesimal_strain/mohr_coulomb.h
- include/materials/infinitesimal_strain/mohr_coulomb.tcc
- include/materials/strain_rate/bingham.tcc
- include/particles/particle.h
- include/particles/particle_base.h
- tests/materials/mohr_coulomb_test.cc
This PR adds a separate yield criterion to fix issues with volume expansion occurring in the current Mohr-Coulomb model.
To use this feature, users need to add the following two material parameters:
1. "packing_fraction" or "porosity" which determines the granular assembly's initial packing fraction or void fraction (or porosity). "porosity" (input for two-phase MPM) will be used if "packing_fraction" is not found.
2. "packing_fraction_minimum", which determines the minimum packing fraction when the material can carry stress. Below this value, the material should not carry any stress. Default "packing_fraction_minimum" is 0.0, which reverts to standard Mohr-Coulomb. 
This PR also fixes the clang-formating issue in bingham.tcc related to #99. …
> [Constitutive] Fixing issues with volume expansion in Mohr-Coulomb model
